"""Aggregate flatwire conformance results into RESULTS.md.

Reads results/<lang>.json from every language that ran, and produces:
  - a per-format round-trip matrix (which cases round-trip in which language),
  - a byte-identity analysis for the 'identical'-tier cases (do all languages
    that ran produce the exact same encoded bytes?),
  - a maturity table (locally-tested vs CI-validated).

The claim we publish is exactly what the data supports - no overclaiming.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / "results"
FORMATS = ["json", "xml", "msgpack"]
LANG_ORDER = ["python", "node", "dotnet", "rust", "go", "java"]
LANG_LABEL = {"python": "Python", "node": "Node", "dotnet": ".NET", "rust": "Rust", "go": "Go", "java": "Java"}


def load():
    data = {}
    for lang in LANG_ORDER:
        p = RESULTS / f"{lang}.json"
        if p.exists():
            data[lang] = json.loads(p.read_text(encoding="utf-8"))
    return data


def main() -> None:
    data = load()
    langs = [l for l in LANG_ORDER if l in data]
    if not langs:
        raise SystemExit("no results/*.json found - run the language runners first")

    # Case order + tier from any available runner (they share the corpus).
    corpus = json.loads((ROOT / "corpus.json").read_text(encoding="utf-8"))
    case_order = [(c["name"], c["tier"]) for c in corpus["cases"]]

    lines = []
    lines.append("# flatwire conformance results\n")
    lines.append("_Generated by [`aggregate.py`](aggregate.py) from every language's "
                 "[`results/`](results) output. Do not edit by hand._\n")
    lines.append(f"Languages reporting: **{', '.join(LANG_LABEL[l] for l in langs)}**.\n")

    # --- Maturity table ---
    lines.append("## Maturity\n")
    lines.append("| Language | Local dev+test | Runs conformance |")
    lines.append("|---|---|---|")
    for l in LANG_ORDER:
        if l in data:
            local = "✅ yes" if data[l].get("tested_locally") else "CI only"
            lines.append(f"| {LANG_LABEL[l]} | {local} | ✅ |")
        else:
            lines.append(f"| {LANG_LABEL[l]} | — | ⏳ not yet reporting |")
    lines.append("")

    # --- Round-trip matrix per format ---
    lines.append("## Round-trip matrix\n")
    lines.append("Every case must decode back to what was encoded, in every language. "
                 "`✓` = round-trips; `✗` = fails; blank = language not reporting.\n")
    for fmt in FORMATS:
        lines.append(f"### {fmt}\n")
        header = "| case | tier | " + " | ".join(LANG_LABEL[l] for l in langs) + " |"
        sep = "|---|---|" + "---|" * len(langs)
        lines.append(header)
        lines.append(sep)
        for name, tier in case_order:
            row = [name, tier]
            for l in langs:
                f = data[l]["cases"].get(name, {}).get("formats", {}).get(fmt, {})
                if not f:
                    row.append("")
                elif f.get("roundtrip"):
                    row.append("✓")
                else:
                    row.append("✗")
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")

    # --- Byte-identity analysis (per format) ---
    lines.append("## Byte-identity across languages\n")
    lines.append("**MessagePack (binary) is canonical**, so flatwire guarantees "
                 "*byte-identical* encoding across every language: same integer "
                 "widths (non-negative→smallest unsigned, negative→smallest signed), "
                 "IEEE-754 floats, length-prefixed UTF-8 strings, and **sorted map "
                 "keys**. **JSON and XML are text**, where escaping, whitespace, "
                 "float formatting and key order legitimately differ across "
                 "ecosystems — so we guarantee *round-trip*, not byte-identity, for "
                 "those. The tables below report what actually holds.\n")
    identical_cases = [n for n, t in case_order if t == "identical"]
    fmt_identity = {}
    for fmt in FORMATS:
        lines.append(f"### {fmt}" + ("  _(byte-identity guaranteed)_" if fmt == "msgpack"
                     else "  _(round-trip only; byte differences expected)_") + "\n")
        lines.append("| case | shared bytes? | SHA-256 (first 12) | note |")
        lines.append("|---|---|---|---|")
        ok = 0
        counted = 0
        for name in identical_cases:
            shas = {}
            for l in langs:
                f = data[l]["cases"].get(name, {}).get("formats", {}).get(fmt, {})
                if f.get("roundtrip") and "sha256" in f:
                    shas[l] = f["sha256"]
            if not shas:
                lines.append(f"| {name} | — | — | no data |")
                continue
            counted += 1
            uniq = set(shas.values())
            if len(uniq) == 1:
                ok += 1
                sha = next(iter(uniq))
                lines.append(f"| {name} | ✅ identical | `{sha[:12]}` | {len(shas)} langs agree |")
            else:
                groups = {}
                for l, s in shas.items():
                    groups.setdefault(s, []).append(LANG_LABEL[l])
                detail = "; ".join(f"{','.join(v)}={k[:8]}" for k, v in groups.items())
                lines.append(f"| {name} | ⚠️ differs | — | {detail} |")
        fmt_identity[fmt] = (ok, counted)
        lines.append("")

    # --- Summary claim ---
    lines.append("## Summary\n")
    all_rt = all(
        f.get("roundtrip")
        for l in langs
        for c in data[l]["cases"].values()
        for f in c["formats"].values()
    )
    lines.append(f"- **Round-trip:** {'all cases round-trip in every reporting language ✅' if all_rt else 'some cases fail — see matrix above ⚠️'}")
    mp_ok, mp_total = fmt_identity.get("msgpack", (0, 0))
    if mp_total:
        claim = "✅" if mp_ok == mp_total else "⚠️"
        lines.append(f"- **MessagePack byte-identity:** {mp_ok}/{mp_total} identical-tier cases "
                     f"are byte-identical across all reporting languages {claim}"
                     + (" — **every value encodes to the same bytes in every language.**" if mp_ok == mp_total else "."))
    for fmt in ("json", "xml"):
        ok, total = fmt_identity.get(fmt, (0, 0))
        if total:
            lines.append(f"- **{fmt.upper()}:** round-trips everywhere; byte-identical in "
                         f"{ok}/{total} cases (text-format differences across ecosystems are expected).")
    lines.append("")

    (ROOT / "RESULTS.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {ROOT / 'RESULTS.md'} from {len(langs)} language(s): {', '.join(langs)}")
    mp_ok, mp_total = fmt_identity.get("msgpack", (0, 0))
    print(f"msgpack byte-identity: {mp_ok}/{mp_total} identical-tier cases")


if __name__ == "__main__":
    main()
